default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/client_handler_rtc
        concurrent_limit: 5
        turn_config:
          turn_provider: "turn_server"
          urls: [ "turn:121.40.166.120:3478" ]
          username: "szr"
          credential: "szr123"
      SileroVad:
        module: vad/silero/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 10000
        buffer_look_back: 5000
        speech_padding: 512
#      XiaoYunKws:
#        module: kws/xiaoyun/kws_handler_xiaoyun
#        model_name: iic/speech_charctc_kws_phone-xiaoyun
#        keywords: 小云小云
#        speaking_threshold: 0.5
      KISXiaoyun:
        module: kis/kis_handler_xiaoyun
        model_name: "iic/speech_charctc_kws_phone-xiaoyun"
        interrupt_keywords: ["小云小云"]
        keywords_threshold: 0.5
      SherpaKws:
        module: kws/sherpa/kws_handler_sherpa
        model_name: "sherpa_kws"
        keywords_file: "library_keyword.txt"
      SenseVoice:
        module: asr/sensevoice/asr_handler_sensevoice
        model_name: "iic/SenseVoiceSmall"
        language: "zh"
        use_itn: False
        batch_size_s: 10
#      LLMOpenAI:
#        module: llm/openai/llm_handler_openai
#        model_name: "qwen-plus"
#        system_prompt: "你是小云，扮演一个 AI 助手，用简短的对话来回答用户的问题，并在对话内容中加入合适的标点符号，不需要加入标点符号相关的内容"
#        api_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
#        api_key: "sk-e13e4e1343d6460bbd5fca38ec1d785d"
#        history_length: 20
      DifyAgent:
        module: llm/dify/llm_handler_dify
        api_url: "http://192.168.86.54:9000/v1"
        api_key: "app-pg2tso9lLe5ED7lVhCdB7qOx"
      CosyVoice:
#        module: tts/cosyvoice/tts_handler_cosyvoice
#        model_name: "iic/CosyVoice-300M-SFT"
#        # ref_audio_path: "CosyVoice/asset/zero_shot_prompt.wav"
#        # ref_audio_text: "希望你以后能够做的比我还好呦。"
#        spk_id: "中文女"
#        speed: 0.8
#        sample_rate: 24000
#        process_num: 1
        module: tts/bailian/tts_handler_cosyvoice
        model_name: "cosyvoice-v1"
        api_key: "sk-e13e4e1343d6460bbd5fca38ec1d785d"

